from enum import Enum

class ErrorCode(str, Enum):
    INVALID_SYMBOL = "INVALID_SYMBOL"
    INVALID_PARAMETER = "INVALID_PARAMETER"
    API_ERROR = "API_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
